# GENERATED by packaging/update.sh — do not edit by hand.
class Incoda < Formula
  desc "Keyed, machine-local job lane for builds, tests and AI-agent fleets"
  homepage "https://github.com/deblasis/incoda"
  version "0.7.1"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/deblasis/incoda/releases/download/v0.7.1/incoda_darwin_arm64"
      sha256 "86f60d1891e91db507cf467faae14d13e87f7f7e563f3a1039bd0bbfb1533638"
    end
    on_intel do
      url "https://github.com/deblasis/incoda/releases/download/v0.7.1/incoda_darwin_amd64"
      sha256 "8d17b3b516335dc6ff7d7ca773cb39b3929ce76691906c23855e34ed63258844"
    end
  end

  def install
    if Hardware::CPU.arm?
      bin.install "incoda_darwin_arm64" => "incoda"
    else
      bin.install "incoda_darwin_amd64" => "incoda"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/incoda version")
  end
end
