# GENERATED by packaging/update.sh — do not edit by hand.
class Incoda < Formula
  desc "Keyed, machine-local job lane for builds, tests and AI-agent fleets"
  homepage "https://github.com/deblasis/incoda"
  version "0.5.0"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/deblasis/incoda/releases/download/v0.5.0/incoda_darwin_arm64"
      sha256 "12a99937b5f1dbd917d7fb40e99bcd1e131c317877241e3eec54199129ed157d"
    end
    on_intel do
      url "https://github.com/deblasis/incoda/releases/download/v0.5.0/incoda_darwin_amd64"
      sha256 "3850634497a74fd12e847ef182ff6b6fc4dc17063e3e374aee115493ad64fada"
    end
  end

  def install
    if Hardware::CPU.arm?
      bin.install "incoda_darwin_arm64" => "incoda"
    else
      bin.install "incoda_darwin_amd64" => "incoda"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/incoda version")
  end
end
