#!/bin/sh
# Regenerate Homebrew and Scoop packaging for a release tag.
#
# usage: ./packaging/update.sh v0.4.0
#
# Writes:
#   packaging/homebrew/incoda.rb
#   packaging/scoop/incoda.json
#
# Copy those into deblasis/homebrew-tap and deblasis/scoop-bucket, or run
# with OUT_TAP and OUT_BUCKET set to the local clone paths.

set -eu

TAG="${1:?usage: $0 vX.Y.Z}"
case "$TAG" in
v*) ;;
*)
	echo "packaging/update.sh: TAG must start with v (e.g. v0.5.0)" >&2
	exit 1
	;;
esac
VER="${TAG#v}"
REPO="${INCODA_REPO:-deblasis/incoda}"
BASE="https://github.com/$REPO/releases/download/$TAG"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT INT TERM

curl -fsSL "$BASE/SHA256SUMS" -o "$WORK/SHA256SUMS"

hash_for() {
	awk -v a="$1" '{ n=$2; sub(/^\*/,"",n); if (n==a) { print $1; exit } }' "$WORK/SHA256SUMS"
}

darwin_amd64="$(hash_for incoda_darwin_amd64)"
darwin_arm64="$(hash_for incoda_darwin_arm64)"
win_amd64="$(hash_for incoda_windows_amd64.exe)"
win_arm64="$(hash_for incoda_windows_arm64.exe)"

for h in "$darwin_amd64" "$darwin_arm64" "$win_amd64" "$win_arm64"; do
	[ -n "$h" ] || { echo "packaging/update.sh: SHA256SUMS missing an asset for $TAG" >&2; exit 1; }
done

ROOT="$(CDPATH= cd "$(dirname "$0")/.." && pwd)"
HB="$ROOT/packaging/homebrew/incoda.rb"
SC="$ROOT/packaging/scoop/incoda.json"
mkdir -p "$(dirname "$HB")" "$(dirname "$SC")"

cat >"$HB" <<EOF
# GENERATED by packaging/update.sh — do not edit by hand.
class Incoda < Formula
  desc "Keyed, machine-local job lane for builds, tests and AI-agent fleets"
  homepage "https://github.com/deblasis/incoda"
  version "$VER"
  license "MIT"
  depends_on :macos

  on_macos do
    on_arm do
      url "$BASE/incoda_darwin_arm64"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$BASE/incoda_darwin_amd64"
      sha256 "$darwin_amd64"
    end
  end

  def install
    if Hardware::CPU.arm?
      bin.install "incoda_darwin_arm64" => "incoda"
    else
      bin.install "incoda_darwin_amd64" => "incoda"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/incoda version")
  end
end
EOF

cat >"$SC" <<EOF
{
  "_comment": "GENERATED by packaging/update.sh — do not edit by hand.",
  "version": "$VER",
  "description": "Keyed, machine-local job lane for builds, tests and AI-agent fleets",
  "homepage": "https://github.com/deblasis/incoda",
  "license": "MIT",
  "architecture": {
    "64bit": {
      "url": "$BASE/incoda_windows_amd64.exe#/incoda.exe",
      "hash": "$win_amd64"
    },
    "arm64": {
      "url": "$BASE/incoda_windows_arm64.exe#/incoda.exe",
      "hash": "$win_arm64"
    }
  },
  "bin": "incoda.exe",
  "checkver": "github",
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/deblasis/incoda/releases/download/v\$version/incoda_windows_amd64.exe#/incoda.exe",
        "hash": {
          "url": "\$baseurl/SHA256SUMS"
        }
      },
      "arm64": {
        "url": "https://github.com/deblasis/incoda/releases/download/v\$version/incoda_windows_arm64.exe#/incoda.exe",
        "hash": {
          "url": "\$baseurl/SHA256SUMS"
        }
      }
    }
  }
}
EOF

printf 'packaging/update.sh: wrote %s and %s for %s\n' "$HB" "$SC" "$TAG"

if [ -n "${OUT_TAP:-}" ]; then
	cp "$HB" "$OUT_TAP/Formula/incoda.rb"
	printf 'packaging/update.sh: copied Homebrew formula to %s\n' "$OUT_TAP/Formula/incoda.rb"
fi
if [ -n "${OUT_BUCKET:-}" ]; then
	cp "$SC" "$OUT_BUCKET/bucket/incoda.json"
	printf 'packaging/update.sh: copied Scoop manifest to %s\n' "$OUT_BUCKET/bucket/incoda.json"
fi
